# Generated by Django 4.2.7 on 2023-12-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSocio', models.DateField(max_length=80)),
                ('fechaIncorporacion', models.DateField()),
                ('anoNacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('estado', models.CharField(choices=[('V', 'Vigente'), ('S', 'Suspendido'), ('R', 'Retirado')], max_length=1)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
