# Generated by Django 4.2.7 on 2023-12-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios_app', '0002_alter_socios_nombresocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1),
        ),
    ]
